### ISSUE TITLE
Transfer function

### ISSUE THREAD

**Issue by SeisPiano** [helenjanisz/ATaCR#17]
Thank you for the code provided. When I calculated the transfer function, I found that there is an error in function `noisecal_dailystaspectra.m`, which will cause all transfer functions related to the H component to be incorrect. This problem is caused by the wrong number of windows used for averaging.
I solved this problem as follows:
The code in line 140 https://github.com/helenjanisz/ATaCR/blob/b94884934487473e897ad1cda184561937b00ea6/function/noisecal_dailystaspectra.m#L140 changed to `if is_goodwin(ista)==0`.
I hope this information is useful for the ATaCR users.
Thanks again.

**Comment by helenjanisz** [comment]
Thank you for finding this error. This bug has now been corrected with your update.
